version: "3.9"

services:
  api-gateway:
    build: ./services/api-gateway.service/
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth
    networks:
      - app-network

  auth:
    build: ./services/auth.service/
    container_name: auth-service
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: ./app
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
