name: OPA Checks
on: [push]

jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Checking Docker containers
        uses: instrumenta/conftest-action@master
        with:
          files: |
            docker-compose.yml
            app/Dockerfile
            services/api-gateway.service/Dockerfile
          policy: policies/containers
