name: GKE CD

on:
  push:
    branches: ["dev"]

env:
  PROJECT_ID: ${{ secrets.GCP_STAGING_PROJECT_ID }}
  REGION: ${{ secrets.GKE_REGION }}
  ARTIFACT_REPO: ${{ secrets.ARTIFACT_REPO }}
  CLUSTER: ${{ secrets.GKE_CLUSTER }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        # Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_STAGING_SA_KEY }}

      - name: Set up GCP
        uses: google-github-actions/setup-gcloud@v2

        # Docker Config
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet

          # Build Docker Images
      - name: Build Docker Images 
        id: build
        run: |
          PROJECT_ID=${PROJECT_ID} \
          REGION=${REGION} \
          ARTIFACT_REPO=${ARTIFACT_REPO} \
          IMAGE_TAG=${IMAGE_TAG} \
          docker compose build

      - name: Upload to GCP Artifact Registry
        id: upload
        run: |
          PROJECT_ID=${PROJECT_ID} \
          REGION=${REGION} \
          ARTIFACT_REPO=${ARTIFACT_REPO} \
          IMAGE_TAG=${IMAGE_TAG} \
          docker compose push

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${CLUSTER} \
          --region ${REGION} \
          --project ${PROJECT_ID}

      - name: Deploy all services to GKE
        run: |
          kubectl apply -f k8s/

          kubectl rollout status deployment/backend
          kubectl rollout status deployment/auth

