name: Production Release Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  prod-release:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- PRODUCTION DEPLOYMENT ---
      - name: Deploy to Production
        id: deploy
        run: |
          echo "Executing Terraform apply..."
          echo "Updating Kubernetes manifests..."
